#!/bin/bash

# Crontab entry ( without hash mark #
# @reboot ( /home/Companion/LauncherCompanion & ) > /dev/null 2>&1

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

if [ -d "/home/RAPMD" ] ; then
    source /home/RAPMD/bin/activate
fi

export OLLAMA_HOST=http://127.0.0.1:11434

BaseDir="/home/Companion"

cd $BaseDir

while true ; do
    $BaseDir/Companion
    sleep 60
done
